In [2]:
from sklearn.datasets import make_regression

In [3]:
x, y = make_regression(n_samples = 100, n_features = 2, n_informative = 2, n_targets = 1, noise = 50)

In [4]:
x

array([[ 0.29822043, -0.07777387],
       [ 0.23570032,  0.57484748],
       [ 0.36484384, -0.9201848 ],
       [-0.38823585, -2.02982232],
       [ 1.47077674,  1.10935316],
       [-0.34504586,  0.62916658],
       [-0.26297722, -1.72365923],
       [ 0.92081672, -0.01506124],
       [ 0.5065813 , -0.78181497],
       [ 0.13766379,  1.32633108],
       [-0.65964136,  0.27136129],
       [ 0.02017022,  0.01332434],
       [-0.05826183,  0.94286669],
       [ 1.1440644 , -2.50524612],
       [ 0.72878947, -0.49000493],
       [-1.08920317, -0.62681433],
       [ 0.64567901,  0.53130066],
       [ 1.93281747, -0.63303676],
       [ 0.43752528,  1.0892686 ],
       [-1.26901869,  0.71986787],
       [ 0.07783604, -0.55972625],
       [ 0.61708216, -0.33300602],
       [-0.07993733, -0.56516545],
       [ 1.3303178 , -1.50693907],
       [-0.29732375,  0.77633279],
       [-0.73273385,  0.68791297],
       [-0.63978432,  0.02011164],
       [ 0.6198087 , -0.07059049],
       [ 1.93336353,

array([  27.63007856,  -69.83222531,  106.8699895 ,  -29.87502383,
         75.00218149,   69.41868482,  -16.33829214,   53.20680607,
        -78.98832934,   17.51167784,  -22.15073419,   22.5051843 ,
         78.13067409,  137.87485526,    4.85148594, -211.41140987,
         74.32085059,  157.16904553,  142.53951298, -132.13723986,
        -58.39259505,  178.3489096 ,   27.62025656,   29.03950855,
          1.26233635,  -51.53831135,   -2.7991429 ,   48.10460387,
        206.13343784,  -43.16676449,  -68.61747269,    0.73060061,
        151.59721608,  -91.99882299,  186.81640369,  -80.9052451 ,
        -80.27290878, -126.98280071,  -59.36398521,   23.08471613,
       -171.01946585,   37.98176089,  265.97068346,  230.09053245,
        155.69782529,  101.19489079,  142.76102612,   52.32406423,
          7.08488593,  -74.37695052,   46.12839914, -225.68967589,
        -58.87694864,  100.32536458,   67.39931307, -154.38510047,
        -32.87773034,   57.01168323,  -47.27266299,  175.68828

In [7]:
import pandas as pd

xyz = pd.read_csv('data.csv')

In [8]:
xyz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [9]:
x, y

(array([[ 0.29822043, -0.07777387],
        [ 0.23570032,  0.57484748],
        [ 0.36484384, -0.9201848 ],
        [-0.38823585, -2.02982232],
        [ 1.47077674,  1.10935316],
        [-0.34504586,  0.62916658],
        [-0.26297722, -1.72365923],
        [ 0.92081672, -0.01506124],
        [ 0.5065813 , -0.78181497],
        [ 0.13766379,  1.32633108],
        [-0.65964136,  0.27136129],
        [ 0.02017022,  0.01332434],
        [-0.05826183,  0.94286669],
        [ 1.1440644 , -2.50524612],
        [ 0.72878947, -0.49000493],
        [-1.08920317, -0.62681433],
        [ 0.64567901,  0.53130066],
        [ 1.93281747, -0.63303676],
        [ 0.43752528,  1.0892686 ],
        [-1.26901869,  0.71986787],
        [ 0.07783604, -0.55972625],
        [ 0.61708216, -0.33300602],
        [-0.07993733, -0.56516545],
        [ 1.3303178 , -1.50693907],
        [-0.29732375,  0.77633279],
        [-0.73273385,  0.68791297],
        [-0.63978432,  0.02011164],
        [ 0.6198087 , -0.070

In [10]:
import plotly.express as px

In [13]:
df = pd.DataFrame({"feature1" : x[:, 0], "feature2" : x[:, 1], 'target' : y })

In [14]:
df

feature1  feature2      target
0   0.298220 -0.077774   27.630079
1   0.235700  0.574847  -69.832225
2   0.364844 -0.920185  106.869990
3  -0.388236 -2.029822  -29.875024
4   1.470777  1.109353   75.002181
..       ...       ...         ...
95  0.194796 -0.683120  -26.828799
96  2.382597 -0.199493  257.687271
97  1.177272  1.000766  101.404141
98  0.402245  0.584834   -5.752356
99  1.749054 -0.659081  278.123550

[100 rows x 3 columns]

In [15]:
xyz = px.scatter_3d(df, x = 'feature1', y = 'feature2', z = 'target')

In [17]:
import plotly.offline as pyo 
pyo.init_notebook_mode(connected=True)

In [18]:
xyz.show()

In [19]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
obj = LinearRegression()

In [26]:
obj.fit(x_train, y_train)

LinearRegression()

In [28]:
obj

LinearRegression()

In [29]:
obj.coef_

array([88.87186291, 10.23444999])

In [32]:
b = obj.intercept_

b

5.778335017693621

In [34]:
y = b + 88.87186291 * 1.14714891 + 10.23444999 * 0.94286669

In [35]:
y

117.3773176706114

In [40]:
y_test

array([ 137.87485526,  278.12355008,  -58.87694864,  -56.44628623,
        175.68828906,  -40.85120762,  -32.87773034,  190.6365294 ,
        187.03827019,  -98.43231121,  101.40414118,  -47.27266299,
        101.19489079,  -53.3939368 ,   23.08471613,  -80.27290878,
         78.13067409,  155.52112544, -211.41140987,   69.41868482])

In [43]:
y = b + (1.74660719 * 88.87186291) + (1.2687787 * 10.23444999)

y

173.98782191852115

In [38]:
x_test

array([[ 1.1440644 , -2.50524612],
       [ 1.74905367, -0.65908147],
       [-1.48937586,  0.22995771],
       [-0.55670983,  0.17839328],
       [ 1.78686866, -0.18918145],
       [ 0.07714021,  1.57715223],
       [ 0.30599568, -0.4639069 ],
       [ 1.67482934, -0.69563664],
       [ 1.74660719,  1.2687787 ],
       [-0.8169447 , -0.56993826],
       [ 1.17727158,  1.00076561],
       [-0.69490294, -1.09537094],
       [ 0.79509678,  1.76523908],
       [-0.05240617,  0.11050845],
       [-0.14211825, -0.49445335],
       [-0.90761704, -0.8816589 ],
       [-0.05826183,  0.94286669],
       [ 1.96760777, -1.11650912],
       [-1.08920317, -0.62681433],
       [-0.34504586,  0.62916658]])

In [45]:
import plotly.graph_objects as go


import numpy as np

x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)

xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

z_final = obj.predict(final).reshape(10,10)

z = z_final

fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()