In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("banknifty_data.csv")

In [3]:
data

Unnamed: 0                       time        open        high  \
0              0  2000-01-03 09:15:00+05:30   1054.8101   1054.8101   
1              1  2000-01-04 09:15:00+05:30   1092.0800   1092.0800   
2              2  2000-01-05 09:15:00+05:30   1055.9900   1055.9900   
3              3  2000-01-06 09:15:00+05:30   1086.6700   1086.6700   
4              4  2000-01-07 09:15:00+05:30   1126.9900   1126.9900   
...          ...                        ...         ...         ...   
5564        5564  2022-06-13 09:15:00+05:30  33728.6480  33774.0510   
5565        5565  2022-06-14 09:15:00+05:30  33180.6020  33618.1480   
5566        5566  2022-06-15 09:15:00+05:30  33317.8010  33554.5510   
5567        5567  2022-06-16 09:15:00+05:30  33648.8010  33756.5000   
5568        5568  2022-06-17 09:15:00+05:30  32393.4490  32889.8010   

             low       close  weekday  range_HL  range_OC  type  
0      1054.8101   1054.8101        0     0.000     0.000   Tie  
1      1092.0800   1092.0800        1     0.000     0.000   Tie  
2      1055.9900   1055.9900        2     0.000     0.000   Tie  
3      1086.6700   1086.6700        3     0.000     0.000   Tie  
4      1126.9900   1126.9900        4     0.000     0.000   Tie  
...          ...         ...      ...       ...       ...   ...  
5564  33210.3520  33405.8520        0   563.699   322.796  bear  
5565  33123.8980  33311.3520        1   494.250   130.750  bull  
5566  33249.5510  33339.0000        2   305.000    21.199  bull  
5567  32537.9490  32617.1000        3  1218.551  1031.701  bear  
5568  32290.5510  32743.0510        4   599.250   349.602  bull  

[5569 rows x 10 columns]

In [5]:
data.count()

Unnamed: 0    5569
time          5569
open          5569
high          5569
low           5569
close         5569
weekday       5569
range_HL      5569
range_OC      5569
type          5569
dtype: int64

In [41]:
df = pd.read_csv('data.csv')

In [43]:
df

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [72]:
x = pd.DataFrame(df.iloc[:, 1])

In [82]:
y = pd.DataFrame(df.iloc[:, -2])

In [83]:
y

Maxpulse
0         130
1         145
2         135
3         175
4         148
..        ...
164       140
165       145
166       145
167       150
168       150

[169 rows x 1 columns]

In [84]:
from sklearn.model_selection import train_test_split

In [85]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [86]:
from sklearn.linear_model import LinearRegression

In [87]:
obj = LinearRegression()

In [88]:
x_train

Pulse
39     104
83     100
71     109
26      92
134    103
..     ...
7      104
87     100
66     105
47     111
146    107

[135 rows x 1 columns]

In [89]:
obj.fit(x_train, y_train)

LinearRegression()

In [91]:
y_pred = obj.predict(x_test)

In [92]:
from sklearn.metrics import r2_score

In [93]:
r2_score(y_test, y_pred)

0.6556126742500435

In [96]:
m = obj.coef_

In [97]:
b = obj.intercept_

In [99]:
b

array([37.2351926])

In [105]:
y = m * 100 + b

y

array([[127.38732529]])

In [104]:
y_train

Maxpulse
39        129
83        130
71        153
26        118
134       136
..        ...
7         134
87        157
66        135
47        136
146       136

[135 rows x 1 columns]

In [106]:
# mutipal liner regression

In [159]:
df

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [183]:
x = pd.DataFrame({"data1":df.iloc[:, 0], "data2" : df.iloc[:,1]})

In [178]:
x

data1  data2
0       60    110
1       60    117
2       60    103
3       45    109
4       45    117
..     ...    ...
164     60    105
165     60    110
166     60    115
167     75    120
168     75    125

[169 rows x 2 columns]

In [171]:
y = pd.DataFrame({"target" : df.iloc[:, 2]})

In [172]:
y

target
0       130
1       145
2       135
3       175
4       148
..      ...
164     140
165     145
166     145
167     150
168     150

[169 rows x 1 columns]

In [173]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [174]:
obj1 = LinearRegression()

In [175]:
newdata = x_test

In [176]:


y_predn = obj.predict(newdata)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- data1
- data2


In [147]:
newdata = pd.DataFrame({"data1": x_test.iloc[:,0]})

In [148]:
import numpy as np

newdata = np.array(x_test)

In [145]:
newdata

array([[ 60, 105],
       [ 20, 106],
       [ 90,  93],
       [ 15, 124],
       [ 30,  95],
       [ 90,  90],
       [ 60, 111],
       [ 45, 100],
       [ 45,  90],
       [ 60, 109],
       [ 25, 152],
       [ 60, 105],
       [ 45,  90],
       [ 30,  92],
       [ 30, 103],
       [ 45, 107],
       [ 60, 100],
       [ 90,  90],
       [150,  97],
       [ 20, 110],
       [ 30,  80],
       [ 45, 111],
       [ 20, 151],
       [300, 108],
       [ 60,  97],
       [ 60, 101],
       [ 45, 104],
       [ 60, 121],
       [ 30, 136],
       [210, 137],
       [ 45, 122],
       [ 60, 100],
       [ 75, 125],
       [ 45, 117]])