In [1]:
import numpy as np

In [26]:
arr = np.array([[[[34, 67, 89, 45], [56, 78, 45, 45]], [[45, 67, 89, 56], [56, 78, 45, 34]]], [[[34, 67, 89, 45], [56, 78, 45, 45]], [[45, 67, 89, 56], [56, 78, 45, 34]]]])

In [27]:
arr

array([[[[34, 67, 89, 45],
         [56, 78, 45, 45]],

        [[45, 67, 89, 56],
         [56, 78, 45, 34]]],


       [[[34, 67, 89, 45],
         [56, 78, 45, 45]],

        [[45, 67, 89, 56],
         [56, 78, 45, 34]]]])

In [30]:
arr.ndim

4

In [29]:
arr.shape

(2, 2, 2, 4)

## Indexing or Slicing....

In [31]:
arr1 = np.array([12, 4, 56, 34, 23, 56, 78, 90, 34, 23])

In [33]:
arr1

array([12,  4, 56, 34, 23, 56, 78, 90, 34, 23])

In [34]:
# arr1[indexnumber]
arr1[4]

23

In [35]:
arr1[8]

34

### Negtive Indexing 

In [36]:
arr1 = np.array([12, 4, 56, 34, 23, 56, 78, 90, 34, 23])

In [37]:
arr1[-3]

90

# Slicing : 

## objectname[start : end : increment]

 Default Values:
    start -> 0
    end -> n - 1
    increment -> 1 

In [39]:
arr1 = np.array([12, 4, 56, 34, 23, 56, 78, 90, 34, 23])

In [40]:
arr1[2 : 8 : 1]

array([56, 34, 23, 56, 78, 90])

In [41]:
arr1 = np.array([12, 4, 56, 34, 23, 56, 78, 90, 34, 23])

In [42]:
arr1[3 : ]

array([34, 23, 56, 78, 90, 34, 23])

In [43]:
arr1[ : 6]

array([12,  4, 56, 34, 23, 56])

In [44]:
arr1[: : -1]

array([23, 34, 90, 78, 56, 23, 34, 56,  4, 12])

## Slicing or indexing with 2-D Ndarray.....

In [47]:
zx = np.array([[23, 45, 56, 67, 4, 3, 6, 34, 23, 45], [45, 67, 78, 45, 34, 2, 12, 12, 34, 22]])

In [48]:
zx

array([[23, 45, 56, 67,  4,  3,  6, 34, 23, 45],
       [45, 67, 78, 45, 34,  2, 12, 12, 34, 22]])

In [49]:
zx.shape

(2, 10)

In [51]:
zx[1][5]

2

In [52]:
pq = np.array([[45, 56, 34, 23, 45], [45, 65, 3, 56, 34], [67, 23, 45, 23, 23]])

In [53]:
pq

array([[45, 56, 34, 23, 45],
       [45, 65,  3, 56, 34],
       [67, 23, 45, 23, 23]])

In [54]:
pq[2][1]

23

In [55]:
pq[1][1 : 4]

array([65,  3, 56])

In [56]:
# With 3D

In [57]:
zx = np.array([[[45, 34, 23, 45], [45, 67, 45, 34]], [[56, 34, 2, 23], [45, 23, 12, 345]]])

In [58]:
zx

array([[[ 45,  34,  23,  45],
        [ 45,  67,  45,  34]],

       [[ 56,  34,   2,  23],
        [ 45,  23,  12, 345]]])

In [60]:
# zx.shape

In [63]:
zx[1][0][2]

2

In [64]:
zx[0][1][1:]

array([67, 45, 34])

In [66]:
# zx.dtype

In [ ]:
type()

# dtype

In [69]:
zx = np.array([34, 56, 3, 56, "car"])

In [70]:
zx.dtype

dtype('<U11')

In [71]:
# python list ---> range()

In [72]:
# arange()

In [73]:
# 1 ----- 20

In [74]:
data = np.arange(1, 21)

In [75]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [76]:
# list