# Reshape Ndarray:------

In [1]:
import numpy as np

In [2]:
# 1D to 2D

In [7]:
arr = np.array([12, 34, 56, 67, 89, 90, 56, 78, 56, 4, 2, 1])

In [8]:
arr

array([12, 34, 56, 67, 89, 90, 56, 78, 56,  4,  2,  1])

In [9]:
arr.ndim

1

In [10]:
arr.shape

(12,)

In [13]:
# np.reshape(objectname, (formt of reshape))

In [14]:
np.reshape(arr, (4, 3))

array([[12, 34, 56],
       [67, 89, 90],
       [56, 78, 56],
       [ 4,  2,  1]])

In [15]:
arr.reshape(3, 4)

array([[12, 34, 56, 67],
       [89, 90, 56, 78],
       [56,  4,  2,  1]])

In [16]:
# -1 spacial perameter......

In [17]:
arr1 = np.array([12, 34, 56, 67, 89, 90, 56, 78, 56, 4, 2, 1])

In [21]:
np.reshape(arr1, (6, -1))

array([[12, 34],
       [56, 67],
       [89, 90],
       [56, 78],
       [56,  4],
       [ 2,  1]])

In [24]:
np.reshape(arr1, (-1, 4))

array([[12, 34, 56, 67],
       [89, 90, 56, 78],
       [56,  4,  2,  1]])

In [27]:
arr1 = np.array([12, 34, 56, 67, 89, 90, 56, 78, 56, 4, 2])

In [29]:
arr1.reshape(11, 1)

array([[12],
       [34],
       [56],
       [67],
       [89],
       [90],
       [56],
       [78],
       [56],
       [ 4],
       [ 2]])

## 2D to 1D reshape

In [30]:
zx = np.array([[12, 34, 45, 67, 100], [45, 67, 78, 9, 90]])

In [31]:
zx

array([[ 12,  34,  45,  67, 100],
       [ 45,  67,  78,   9,  90]])

In [32]:
zx.shape

(2, 5)

In [35]:
q = zx.reshape(10)

In [38]:
q

array([ 12,  34,  45,  67, 100,  45,  67,  78,   9,  90])

In [39]:
zx = np.array([[12, 34, 45, 67, 100], [45, 67, 78, 9, 90]])

In [40]:
zx.reshape(-1)

array([ 12,  34,  45,  67, 100,  45,  67,  78,   9,  90])

# 1D to 3D reshape

In [49]:
arr1 = np.array([12, 34, 56, 67, 89, 90, 56, 78, 56, 4, 2, 23, 45, 78, 34, 34])

In [50]:
len(arr1)

16

In [52]:
w = arr1.reshape(2, 2, 4)

In [53]:
w

array([[[12, 34, 56, 67],
        [89, 90, 56, 78]],

       [[56,  4,  2, 23],
        [45, 78, 34, 34]]])

In [54]:
w.shape

(2, 2, 4)

In [55]:
w.ndim

3

# 3D to 1D rehspae

In [60]:
xyz = np.array([[[1, 2, 3, 4], [45, 67, 78, 89]], [[45, 67, 54, 3], [45, 67, 3, 2]]])

In [61]:
xyz.ndim

3

In [62]:
xyz.shape

(2, 2, 4)

In [67]:
xyz

array([[[ 1,  2,  3,  4],
        [45, 67, 78, 89]],

       [[45, 67, 54,  3],
        [45, 67,  3,  2]]])

In [66]:
np.reshape(xyz, -1)

# xyz.reshape(-1)

array([ 1,  2,  3,  4, 45, 67, 78, 89, 45, 67, 54,  3, 45, 67,  3,  2])

In [68]:
# 3d to 2d

In [69]:
xyz

array([[[ 1,  2,  3,  4],
        [45, 67, 78, 89]],

       [[45, 67, 54,  3],
        [45, 67,  3,  2]]])

In [70]:
xyz.reshape(4, 4)

array([[ 1,  2,  3,  4],
       [45, 67, 78, 89],
       [45, 67, 54,  3],
       [45, 67,  3,  2]])

# random::::::------