In [1]:
import numpy as np

In [ ]:
[[12, 34],
 [34, 45], 
 .
.
.
.
..
[23, 67]]

In [2]:
from numpy import random

In [3]:
xyz = random.randint(300, size = (200, 2))

In [4]:
xyz

array([[ 72, 294],
       [ 37, 224],
       [ 41, 160],
       [187,  22],
       [152, 230],
       [ 69, 146],
       [ 88, 235],
       [262,  44],
       [204, 131],
       [189, 209],
       [241, 118],
       [132, 247],
       [ 90, 184],
       [210, 257],
       [174, 132],
       [ 58,   7],
       [129,  31],
       [150,  83],
       [146, 216],
       [ 32, 106],
       [282, 188],
       [192,  29],
       [ 42, 133],
       [259, 289],
       [174, 161],
       [229, 254],
       [296, 178],
       [263, 196],
       [ 45, 213],
       [ 92, 224],
       [ 24, 227],
       [ 96,  90],
       [  3,  49],
       [231, 290],
       [ 41, 205],
       [ 96, 298],
       [163, 108],
       [297, 161],
       [ 76,   5],
       [116,  42],
       [ 82,  30],
       [ 59,   8],
       [265, 219],
       [ 29, 183],
       [123, 140],
       [263, 157],
       [224, 204],
       [256, 244],
       [118, 297],
       [  6,   2],
       [124, 228],
       [ 30,  48],
       [108,

In [5]:
xyz

array([[ 72, 294],
       [ 37, 224],
       [ 41, 160],
       [187,  22],
       [152, 230],
       [ 69, 146],
       [ 88, 235],
       [262,  44],
       [204, 131],
       [189, 209],
       [241, 118],
       [132, 247],
       [ 90, 184],
       [210, 257],
       [174, 132],
       [ 58,   7],
       [129,  31],
       [150,  83],
       [146, 216],
       [ 32, 106],
       [282, 188],
       [192,  29],
       [ 42, 133],
       [259, 289],
       [174, 161],
       [229, 254],
       [296, 178],
       [263, 196],
       [ 45, 213],
       [ 92, 224],
       [ 24, 227],
       [ 96,  90],
       [  3,  49],
       [231, 290],
       [ 41, 205],
       [ 96, 298],
       [163, 108],
       [297, 161],
       [ 76,   5],
       [116,  42],
       [ 82,  30],
       [ 59,   8],
       [265, 219],
       [ 29, 183],
       [123, 140],
       [263, 157],
       [224, 204],
       [256, 244],
       [118, 297],
       [  6,   2],
       [124, 228],
       [ 30,  48],
       [108,

In [7]:
xyz = random.randint(300, size = (5, 4))

In [8]:
xyz

array([[ 68, 216, 117,  30],
       [105,  33,  75, 147],
       [123,  22, 299, 144],
       [ 41, 153, 268, 279],
       [ 35,  71, 263, 283]])

In [9]:
xyz[2][:]

array([123,  22, 299, 144])

In [13]:
# xyz[0[0]]

In [14]:
xyz[:, 0]

array([ 68, 105, 123,  41,  35])

In [16]:
# question : 

1 ----- 100

2

In [ ]:
odd --> 3
even --> 2