## Numpy : 

In [ ]:
Numpy -> Numarical Python

python -> 1991

Numpy --> 2005
Author of Numpy ---> Travis Oliphant

In [3]:
Array ---> array is the collection of homogeneous (same) data in continuing memory location..

List -> collection of heterogeneous (different) data of data...



In [ ]:
lst = [10, 34, "hlo", True, 100, "hey"]

In [ ]:
List = [12, 56, 34, 23, 12, 100]

In [5]:
Numpy : 

70% -> python
30% -> C/C#

50x times faster then list

In [ ]:
Numpy : help us to working with arrays...

In [ ]:
# installing numpy in jupyter

In [6]:
!pip install numpy

DEPRECATION: Loading egg at c:\users\17nru\appdata\local\programs\python\python312\lib\site-packages\darkflow-0.1.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [9]:
import numpy as np

In [11]:
np.version.version

'1.26.4'

# ndarrays in numpy

In [ ]:
ndarray -> N - Dimetional Arrays

### Ndarray -> when we create an object with the help of array method in numpy, that object is called ndarray.

In [12]:
ar = np.array(100)

In [13]:
ar

array(100)

In [14]:
type(ar)

numpy.ndarray

## check demensions of an ndarray::::::

attribute -> ndim

In [15]:
ar.ndim

0

### Create 1-D Ndarray:

In [16]:
arr = np.array([12, 45, 23, 56, 90])

In [17]:
arr

array([12, 45, 23, 56, 90])

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr.ndim

1

## check shape of an ndarray.....

attribute --> shape

In [20]:
arr.shape

(5,)

## create 2 dimetational ndarray

In [34]:
arr1 = np.array([[12, 45, 67, 89], [34, 56, 78, 45], [45, 67, 89, 34]])

In [30]:
arr1

array([[12, 45, 67, 89],
       [34, 56, 78, 45],
       [45, 67, 89, 34]])

In [31]:
arr1.ndim

2

In [32]:
arr1.shape # (number of rows, number of columns)

(3, 4)

## 3-D Ndarray 

In [44]:
arr2 = np.array([[[23, 45, 45, 67], [45, 67, 34, 23]], [[23, 45, 67, 45], [56, 78, 56, 34]]]) 

In [45]:
arr2

array([[[23, 45, 45, 67],
        [45, 67, 34, 23]],

       [[23, 45, 67, 45],
        [56, 78, 56, 34]]])

In [46]:
arr2.ndim

3

In [47]:
arr2.shape

(2, 2, 4)

In [48]:
xyz = np.array([[[[[34]]]]])

In [50]:
xyz.ndim

5