# Numpy : |

In [1]:
import numpy as np

In [ ]:
List : 
    # new emenets add doooo...
    

In [2]:
arr = np.array([12, 34, 56, 78, 45, 34, 23, 56, 79])

## replace element in numpy

In [ ]:
# objename[indexnumber] = newelement

In [3]:
arr[2] = 100

In [4]:
arr

array([ 12,  34, 100,  78,  45,  34,  23,  56,  79])

In [5]:
xyz = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [7]:
xyz[[2, 5, 8]] = [30, 60, 90]

In [8]:
xyz

array([ 1,  2, 30,  4,  5, 60,  7,  8, 90, 10])

In [9]:
xyz = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [10]:
a = [3, 4, 5]

In [11]:
values = [100, 300, 500]

In [12]:
xyz[a] = values

In [13]:
xyz

array([  1,   2,   3, 100, 300, 500,   7,   8,   9,  10])

## Adding New Element in Ndarray....

In [16]:
zx = np.array([34, 45, 6, 45, 3, 23, 45, 23])

In [17]:
zx

array([34, 45,  6, 45,  3, 23, 45, 23])

In [ ]:
# append()

In [ ]:
# np.append(objectname, newelement, axis)

In [18]:
qw = np.append(zx, 120)

In [19]:
qw

array([ 34,  45,   6,  45,   3,  23,  45,  23, 120])

In [20]:
np.append(zx, [100, 200, 300, 400])

array([ 34,  45,   6,  45,   3,  23,  45,  23, 100, 200, 300, 400])

In [21]:
# Adding new element :--------------

In [24]:
pqr = np.array([2, 4, 5, 6, 8, 2, 3, 6, 7, 8])

In [25]:
# np.insert(objectname, indexnumber, newelment)

In [26]:
np.insert(pqr, 1, 300)

array([  2, 300,   4,   5,   6,   8,   2,   3,   6,   7,   8])

In [27]:
pqr = np.array([2, 4, 5, 6, 8, 2, 3, 6, 7, 8])

In [28]:
indexes = [2, 5, 7]
addedvalues = [300, 5000, 3444]

In [29]:
np.insert(pqr, indexes, addedvalues)

array([   2,    4,  300,    5,    6,    8, 5000,    2,    3, 3444,    6,
          7,    8])

In [30]:
np.insert(pqr, [2, 5, 7], [300, 5000, 3444])

array([   2,    4,  300,    5,    6,    8, 5000,    2,    3, 3444,    6,
          7,    8])

# concatenation in ndarray

In [32]:
zx = np.array([34, 56, 34, 23, 45, 200])


In [33]:
ab = np.array([45, 67, 34, 23, 45, 23])

In [34]:
pq = zx + ab

In [35]:
pq

array([ 79, 123,  68,  46,  90, 223])

In [37]:
np.concatenate((zx, ab))

array([ 34,  56,  34,  23,  45, 200,  45,  67,  34,  23,  45,  23])

In [38]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [39]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

    Join a sequence of arrays along an existing axis.

    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.20.0

    casting : {'no', 'equiv', 'safe', 'same_kind', 

In [40]:
zx = np.array([34, 56, 34, 23, 45, 200])
ab = np.array([45, 67, 34, 23, 45, 23])

In [44]:
# help(np.vstack)

In [45]:
np.vstack((zx, ab))

array([[ 34,  56,  34,  23,  45, 200],
       [ 45,  67,  34,  23,  45,  23]])

# where()

In [ ]:
to know about index number of a elmenet

In [47]:
zx = np.array([34, 56, 34, 23, 34, 23, 34, 45, 56, 78, 34, 23, 12, 4, 56, 23])

In [54]:
# np.where(zx, 4)

In [53]:
# np.where((zx, 4))

In [52]:
# help(np.where)

In [57]:
zx = np.array([34, 56, 34, 23, 34, 23, 34, 45, 56, 78, 34, 23, 12, 4, 56, 23])

In [60]:
np.where(zx == 34)

(array([ 0,  2,  4,  6, 10], dtype=int64),)

In [61]:
# delete elements from ndarray......

In [62]:
zx = np.array([34, 56, 34, 23, 34, 23, 34, 45, 56, 78, 34, 23, 12, 4, 56, 23])

In [63]:
# np.delete(objectname, index_of_element_to_delete)

In [64]:
np.delete(zx, 9)

array([34, 56, 34, 23, 34, 23, 34, 45, 56, 34, 23, 12,  4, 56, 23])

In [65]:
np.delete(zx, [2, 3, 4, 5, 6, 7, 8, 9, 10])

array([34, 56, 23, 12,  4, 56, 23])

In [69]:
zx = np.array([34, 56, 34, 23, 34, 23, 34, 45, 56, 78, 34, 23, 12, 4, 56, 23])

In [70]:
rt = np.where(zx == 34)

In [68]:
rt

(array([ 0,  2,  4,  6, 10], dtype=int64),)

In [71]:
np.delete(zx, rt)

array([56, 23, 23, 45, 56, 78, 23, 12,  4, 56, 23])

In [74]:
zx = np.array([34, 56, 34, 23, 34, 23, 34, 45, 56, 78, 34, 23, 12, 4, 56, 23])

In [78]:
zx[zx > 50]

array([56, 56, 78, 56])

In [80]:
p = zx[zx == 34]

In [81]:
p

array([34, 34, 34, 34, 34])

In [77]:
np.delete(zx, [zx > 34])

ValueError: boolean array argument obj to delete must be one dimensional and match the axis length of 16