In [1]:
import numpy as np

In [4]:
zx = np.array([])

In [ ]:
array["2 x 1 = 2", "2 x 2 = 4", "2 x 3 = 6", . .. . . . . ., "2 x 10 = 20"]

In [9]:
for i in np.arange(1, 11):
    zx = np.append(zx, f"2 x {i} = {2*i}")

In [10]:
zx

array(['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6', '2 x 4 = 8', '2 x 5 = 10',
       '2 x 6 = 12', '2 x 7 = 14', '2 x 8 = 16', '2 x 9 = 18',
       '2 x 10 = 20'], dtype='<U32')

## unique

In [12]:
arr = np.array([12, 45, 67, 34, 23, 3, 45, 56, 34, 23, 2, 2, 34, 45, 3, 4, 3, 3, 3, 56, 67])

In [15]:
# zx = {12, 45, 67, 34, 23, 3, 45, 56, 34, 23, 2, 2, 34, 45, 3, 4, 3, 3, 3, 56, 67}

In [16]:
# zx

In [17]:
arr

array([12, 45, 67, 34, 23,  3, 45, 56, 34, 23,  2,  2, 34, 45,  3,  4,  3,
        3,  3, 56, 67])

In [18]:
np.unique(arr)

array([ 2,  3,  4, 12, 23, 34, 45, 56, 67])

In [19]:
# zeros()

In [29]:
xyz = np.zeros((3, 5))

In [30]:
xyz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
xyz = np.zeros((3, 5), int)

In [36]:
xyz

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## ones funcation

In [43]:
hey = np.ones((3, 4, 5))

In [44]:
hey

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## transpose:::::

In [45]:
xyz = np.array([[12, 34, 56, 67], [67, 89, 56, 45]])

In [46]:
xyz

array([[12, 34, 56, 67],
       [67, 89, 56, 45]])

In [49]:
xyz.transpose()

array([[12, 67],
       [34, 89],
       [56, 56],
       [67, 45]])

In [48]:
np.transpose(xyz)

array([[12, 67],
       [34, 89],
       [56, 56],
       [67, 45]])

In [50]:
help(np.sum)

Help on _ArrayFunctionDispatcher in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.

    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.

        .. versionadded:: 1.7.0

        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [51]:
a = np.array([3, 5, 6, 3, 4])
b = np.array([1, 2, 1, 2, 3])

In [52]:
a + b

array([4, 7, 7, 5, 7])

In [55]:
np.sum(a)

21

In [56]:
np.sum(b)

9

In [57]:
np.sum((a, b))

30

## min and max......

In [58]:
zx = np.array([34, 5, 67, 89, 45, 34, 23, 23, 34, 45, 67, 78, 45, 67, 34, 56, 34])

In [59]:
zx.min()

5

In [60]:
np.min(zx)

5

In [61]:
zx.max()

89

In [62]:
np.max(zx)

89

## mean(), median(), mode()

In [64]:
zx = np.array([34, 5, 67, 89, 45, 34, 23, 23, 34, 45, 67, 78, 45, 67, 34, 56, 34])

In [65]:
np.mean(zx)

45.88235294117647

In [66]:
help(np.median)

Help on _ArrayFunctionDispatcher in module numpy:

median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
    Compute the median along the specified axis.

    Returns the median of the array elements.

    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : {int, sequence of int, None}, optional
        Axis or axes along which the medians are computed. The default
        is to compute the median along a flattened version of the array.
        A sequence of axes is supported since version 1.9.0.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    overwrite_input : bool, optional
       If True, then allow use of memory of input array `a` for
       calculations. The input array will be modified by the call to
       `me

In [71]:
zx = np.array([3, 2, 1, 0, 3, 4])

In [72]:
np.median(zx)

2.5

In [73]:
x = np.sort(zx)

In [74]:
x

array([0, 1, 2, 3, 3, 4])

In [75]:
# mode()

In [76]:
# np.mo

In [77]:
# np.linspace

In [80]:
np.linspace(1, 2, 10)
# np.linspace(start range, end range, number of elements)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [81]:
# dot() product

In [82]:
zx = np.array([1, 3, 5])
ab = np.array([4, 3, 1])

In [83]:
np.dot(zx, ab)

18

In [90]:
zx = np.array([[1, 3], [3, 2]])
ab = np.array([[4, 3], [2, 1]])

In [91]:
np.dot(zx, ab)

array([[10,  6],
       [16, 11]])

In [92]:
zx

array([[1, 3],
       [3, 2]])

In [93]:
ab

array([[4, 3],
       [2, 1]])

In [94]:
# 4+6   3+3


In [95]:
# reshape
# random 

In [96]:
zx = np.array([34, 5, 67, 89, 45, 34, 23, 23, 34, 45, 67, 78, 45, 67, 34, 56, 34])

In [98]:
np.array_split(zx, 3)

[array([34,  5, 67, 89, 45, 34]),
 array([23, 23, 34, 45, 67, 78]),
 array([45, 67, 34, 56, 34])]

In [100]:
np.eye(10, 10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
zx = 