In [1]:
import numpy as np

In [2]:
zx = np.array([23, 45, 67, 34, 23, 45, 23, 12, 45, 67])

In [3]:
zx

array([23, 45, 67, 34, 23, 45, 23, 12, 45, 67])

In [4]:
pq = zx.max()

In [5]:
pq

67

In [6]:
np.where(zx == pq)

(array([2, 9], dtype=int64),)

In [7]:
zx = np.array([23, 45, 67, 34, 23, 45, 23, 12, 45, 67])

In [9]:
np.where(zx == zx.max())

(array([2, 9], dtype=int64),)

In [10]:
# Occurence of ements:

In [11]:
xyz = np.array(["car", "dog", "car", "bus", "car"])

In [13]:
pq = np.unique(xyz)
pq

array(['bus', 'car', 'dog'], dtype='<U3')

In [17]:
for i in pq:
    zx = 0
    for j in xyz:
        if i == j:
            zx = zx + 1
    print(i, zx)
    zx = 0
    

bus 1
car 3
dog 1


In [21]:
mtx = np.arange(1, 37)

In [27]:
mtx = np.array([ 1,  2,  3,  4,  5,  55,  7,  8,  9, 10, 11, 12, 13, 33, 15, 16, 17,
       18, 33, 20, 21, 33, 23, 24, 25, 55, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [49]:
new_mtrx = np.reshape(mtx, (6, 6))

In [29]:
new_mtrx

array([[ 1,  2,  3,  4,  5, 55],
       [ 7,  8,  9, 10, 11, 12],
       [13, 33, 15, 16, 17, 18],
       [33, 20, 21, 33, 23, 24],
       [25, 55, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [139]:
for i in new_mtrx:
    zx = np.max(i)
    index_of_ma_element = np.where(i == zx)
    print(index_of_ma_element)
    i = list(i)
    i[index_of_ma_element] = "MAX"

(array([5], dtype=int64),)


TypeError: list indices must be integers or slices, not tuple

In [44]:
zx = np.array(["23", "45", "67"])

In [45]:
zx[1] = "sdf"


In [46]:
zx

array(['23', 'sd', '67'], dtype='<U2')

## Numpy Random

In [51]:
# import random

In [52]:
from numpy import random

In [53]:
# if we have to genate a random number....

In [73]:
value = random.randint(3, 11)

In [74]:
value

3

In [75]:
# ndarray genaraition.....

In [78]:
arr = random.randint(5, 50, size = (10))

In [79]:
arr

array([35, 27, 30, 38, 21, 16, 30, 22, 33, 35])

In [80]:
arr = random.randint(5, 50, size = (5, 6))
arr

array([[ 6, 27, 48, 24, 20, 44],
       [27, 17, 18, 15, 19, 45],
       [28, 40,  9, 38, 10,  7],
       [ 9, 23, 44, 47,  5, 21],
       [35, 29, 16,  8, 49, 14]])

In [ ]:
# rand() ---> 0, 1

In [89]:
xyz = random.rand()

In [90]:
xyz

0.9331777126143993

In [97]:
xyz = random.rand(3, 4)

In [98]:
xyz

array([[0.02241224, 0.51022365, 0.69534746, 0.41105744],
       [0.07108286, 0.80228668, 0.82545206, 0.15223227],
       [0.72897919, 0.09924921, 0.9446679 , 0.91702769]])

## choice()

In [106]:
random.choice([12, 34, 56, 34, 67, 23])

12

In [108]:
random.choice([12, 34, 56, 34, 67, 23], size = (3, 4))

array([[34, 34, 34, 56],
       [34, 34, 34, 34],
       [67, 56, 56, 23]])

In [109]:
# shuffle()

In [119]:
zx = np.array([1, 2, 3, 4, 5, 6, 7])

In [120]:
random.shuffle(zx)

In [121]:
zx

array([3, 2, 7, 4, 1, 5, 6])

In [126]:
random.random()

0.4415035470853116

In [127]:
help(random.uniform)

Help on built-in function uniform:

uniform(...) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)

    Draw samples from a uniform distribution.

    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.

    .. note::
        New code should use the `~numpy.random.Generator.uniform`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than or equal to high.  The high limi

In [131]:
random.random_sample()

0.649252981612421

In [134]:
zx = np.array([12, 45, 67, 43])

In [135]:
zx.max()

67

In [136]:
print(type(list(zx)))

<class 'list'>


In [138]:
list(zx)


[12, 45, 67, 43]

In [141]:
zx = np.array([[34, 56, 7, 45], [34, 5, 34, 23]])

In [142]:
zx

array([[34, 56,  7, 45],
       [34,  5, 34, 23]])

In [143]:
zx.flatten()

array([34, 56,  7, 45, 34,  5, 34, 23])