In [1]:
# List ---> mutable

# Numpy array ----> mutable....

In [15]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34])

In [16]:
arr

array([12, 34, 56, 67, 89,  5, 34, 34])

### How to add elements in the numpy array

In [17]:
# append() -----> to add new element at the end of the list

In [18]:
# syntax ::  np.append(array_name, new_elements)

In [19]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34])

In [23]:
xyz = np.append(arr, 1000)
xyz

array([  12,   34,   56,   67,   89,    5,   34,   34, 1000])

In [21]:
arr

array([12, 34, 56, 67, 89,  5, 34, 34])

In [24]:
# add multiple elements at the end of the ndarray

In [25]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34])

In [26]:
# synatx :: 
# np.append(array_name, [new_element1, new_element2, ..,..,..])

In [28]:
q = np.append(arr, [1000, 2000, 3000, 10000])

In [29]:
q

array([   12,    34,    56,    67,    89,     5,    34,    34,  1000,
        2000,  3000, 10000])

In [30]:
# next ---> add elements at a prticuler location.

In [36]:
# x = [2, 3, 10, 56, 34, 100]
# x.insert(2, 1000)
# x

In [ ]:
# syntax ::

# np.insert(array_name, index_number, new_element)

In [37]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34])

In [40]:
zx = np.insert(arr, 4, 1000)

In [41]:
zx

array([  12,   34,   56,   67, 1000,   89,    5,   34,   34])

In [42]:
# for example---> multiple elements

In [43]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34])

In [44]:
index_numbers = [1, 3, 7]

new_eleemnts = [1000, 3000, 70000]

In [45]:
np.insert(arr, index_numbers, new_eleemnts)

array([   12,  1000,    34,    56,  3000,    67,    89,     5,    34,
       70000,    34])

In [ ]:
For example :::::

genrate a table 2, in the numpy array.

# output:

['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6', . . . . . . . . ., '2 x 10 = 20']

In [52]:
tbl = np.array([])

In [55]:
for i in range(1, 11):
    x = f"2 x {i} = {2*i}"

    tbl = np.append(tbl, x)

In [56]:
tbl

array(['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6', '2 x 4 = 8', '2 x 5 = 10',
       '2 x 6 = 12', '2 x 7 = 14', '2 x 8 = 16', '2 x 9 = 18',
       '2 x 10 = 20'], dtype='<U32')

In [57]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34])

In [58]:
# how we delete elements from a ndarray

In [ ]:
in list---
    1) pop() ---> it delets last element
    2) remove() -----> remove a spacific element

In [59]:
# delete

In [ ]:
syntax :

np.delete(arrar_name, index)

In [60]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34])

In [64]:
np.delete(arr, 1)

array([12, 56, 67, 89,  5, 34, 34])

In [66]:
np.delete(arr, [1, 3, 6])

array([12, 56, 89,  5, 34])

In [67]:
# last elemnt

In [68]:
np.delete(arr, -1)

array([12, 34, 56, 67, 89,  5, 34])

In [ ]:
# 3:42 PM

In [69]:
# replace elements from a given ndarray

In [70]:
# there is no method to replace the elements from a array...... but we have syntax

In [71]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34])

In [72]:
# 56 ----> 10

In [75]:
# arr[index_number] = new_element

In [76]:
arr[2] = 10

In [77]:
arr

array([12, 34, 10, 67, 89,  5, 34, 34])

In [78]:
# where() -----> help to get index number

In [79]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34, 34, 56, 4])

In [80]:
# np.where(condation)

# condations ----->
# condatioanl operaotrs
# ==
# !=
# >
# <
# >=
# <=

In [81]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34, 34, 56, 4])

In [83]:
np.where(arr == 4)

(array([10], dtype=int64),)

In [84]:
np.where(arr == 34)

(array([1, 6, 7, 8], dtype=int64),)

In [85]:
np.where(arr == 56)

(array([2, 9], dtype=int64),)

In [86]:
arr = np.array([12, 34, 56, 67, 89, 5, 34, 34, 34, 56, 4])

In [87]:
np.where(arr > 50)

(array([2, 3, 4, 9], dtype=int64),)

In [ ]:
resize
reshape

random