In [1]:
import numpy as np

In [2]:

# reshape() ---> method

# random

In [3]:
arr = np.array([12, 34, 45, 67, 78, 8, 45, 34, 23, 45])

In [4]:
arr.ndim

1

In [5]:
# reshape()

In [6]:
# syntax ::

# np.reshape(array_name, new_shape)

In [7]:
# 1D ---- to ---- 2D

In [8]:
arr = np.array([12, 34, 45, 67, 78, 8, 45, 34, 23, 45])

In [9]:
len(arr)

# 5 x 2
# 2 x 5

10

In [10]:
y = np.reshape(arr, (2, 5))
y

array([[12, 34, 45, 67, 78],
       [ 8, 45, 34, 23, 45]])

In [11]:
y.ndim

2

In [16]:
arr = np.array([100, 23, 45, 67, 34 , 34, 67, 23, 12])

In [14]:
len(arr)

9

In [19]:
np.reshape(arr, (3, 4))

ValueError: cannot reshape array of size 9 into shape (3,4)

In [20]:
# -1 ----> 

In [23]:
arr = np.array([78, 8, 45, 34, 23, 45])

In [27]:
np.reshape(arr, (-1, 2))

array([[78,  8],
       [45, 34],
       [23, 45]])

In [28]:
arr = np.array([78, 8, 45, 34, 23, 45, 34, 56, 34, 57, 23, 12])

In [29]:
len(arr)

12

In [31]:
np.reshape(arr, (-1, 2))

array([[78,  8],
       [45, 34],
       [23, 45],
       [34, 56],
       [34, 57],
       [23, 12]])

In [32]:
arr = np.array([78, 8, 45, 34, 23, 45, 34, 56, 34, 57, 23, 12])

In [34]:
np.reshape(arr, (6, -1))

array([[78,  8],
       [45, 34],
       [23, 45],
       [34, 56],
       [34, 57],
       [23, 12]])

In [35]:
# 2D ---> 1D 

In [39]:
x = np.array([[23, 34, 45, 67, 34], [45, 67, 7, 89, 45]])

In [40]:
x.ndim

2

In [41]:
np.reshape(x, -1)

array([23, 34, 45, 67, 34, 45, 67,  7, 89, 45])

In [42]:
# flatten ----> convert to 1 D

In [43]:
# array_name.flatten()

In [44]:
x = np.array([[23, 34, 45, 67, 34], [45, 67, 7, 89, 45]])

In [45]:
x.flatten()

array([23, 34, 45, 67, 34, 45, 67,  7, 89, 45])

In [46]:
# 1D -----> 3D

In [49]:
qw = np.array([[[12, 3, 45], [34, 5, 67]], [[45, 56, 67], [3, 1, 3]]])

In [50]:
qw.ndim

3

In [51]:
qw

array([[[12,  3, 45],
        [34,  5, 67]],

       [[45, 56, 67],
        [ 3,  1,  3]]])

In [52]:
np.reshape(qw, -1)

array([12,  3, 45, 34,  5, 67, 45, 56, 67,  3,  1,  3])

In [53]:
qw.flatten()

array([12,  3, 45, 34,  5, 67, 45, 56, 67,  3,  1,  3])

In [54]:
# 1D -----> 3D

In [61]:
zx = np.array([12, 34, 45, 67, 78, 34, 56, 34, 56, 78, 90, 7, 34, 56, 78, 45, 4, 23])

In [62]:
len(zx)

18

In [63]:
# 3, 3, 2

In [64]:
np.reshape(zx, (3, 3, 2))

array([[[12, 34],
        [45, 67],
        [78, 34]],

       [[56, 34],
        [56, 78],
        [90,  7]],

       [[34, 56],
        [78, 45],
        [ 4, 23]]])

In [65]:
# Numpy ---> random

# Python ----> random


In [66]:
from numpy import random

In [67]:
# random ---> to get or genarte data randomly

In [68]:
# 20 --- 500

In [76]:
random.randint(100)

6

In [80]:
random.randint(50, 100)

88

In [81]:
# 1-D array 

In [87]:
zx = random.randint(10, 40, size = 6)
zx

array([15, 29, 28, 12, 17, 10])

In [88]:
# 2-D

In [90]:
random.randint(2, 6, size = (3, 4))

array([[3, 5, 2, 4],
       [2, 4, 4, 5],
       [2, 4, 4, 4]])

In [91]:
random.randint(2, 6, size = (3, 4, 3))

array([[[5, 5, 5],
        [4, 5, 3],
        [5, 4, 4],
        [5, 2, 3]],

       [[2, 3, 4],
        [2, 2, 2],
        [2, 5, 2],
        [2, 2, 4]],

       [[3, 2, 2],
        [3, 4, 4],
        [5, 2, 2],
        [4, 2, 3]]])

In [92]:
# random.randint(starting_point, end_point, size/shape)

# to genrate integers from a given range

In [93]:
# random.rand() -----> 

# it genrate the random element from the range of 0 to 1

In [98]:
random.rand()

0.4546170184312893

In [99]:
random.rand(6)

array([0.54018357, 0.66357859, 0.87791868, 0.95301682, 0.87110615,
       0.64050068])

In [101]:

random.rand(2, 5)

array([[0.06340842, 0.06212469, 0.91688272, 0.27963004, 0.36097613],
       [0.38989261, 0.50770703, 0.44799551, 0.20159274, 0.51553353]])

In [102]:
# choice

In [108]:
zx = random.choice([12, 34, 34, 45, 6, 76])
zx

34

In [111]:
zx = random.choice([12, 34, 34, 45, 6, 76], size = 5)
zx

array([34, 45, 34, 12,  6])

In [112]:
zx = random.choice([12, 34, 34, 45, 6, 76], size = (3, 4))
zx

array([[76, 12, 34, 45],
       [12, 34, 12, 34],
       [34,  6, 34, 45]])

In [113]:
# shuffle

In [117]:
x = np.array([12, 34, 45, 56, 67, 8, 90])

In [118]:
random.shuffle(x)

In [119]:
x

array([56, 12, 45, 34, 90,  8, 67])