# this is my numpy first class

## this is my numpy first class

### this is my numpy first class

#### this is my numpy first class

In [5]:
# jupyter notebook .

In [6]:
# Numpy -> Numarical Python

In [7]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [9]:
import numpy as np

In [ ]:
# numpy help us to create ndarray

### ndarray ::::

In [10]:
# when we create an object in numpy with the help of array method is called ndarray.

In [13]:
arr = np.array(12)

In [14]:
type(arr)

numpy.ndarray

In [15]:
x = [12, 23, 34, 4]

In [16]:
type(x)

list

In [17]:
# ndarray --> n diamtional array

In [18]:
# human maximum visualize 3-D

In [19]:
# 1-d array

# 0D, 1D, 2D ,-----, nd

In [20]:
# Create 0-D array

In [21]:
import numpy as np

In [22]:
# arrtributes : 
    # 1) ndim ----> to check dimmessions of aray
    # 2) shape ---> return the shape of ndarray

In [23]:
# 0-D array

arr = np.array(100)

In [24]:
arr

array(100)

In [25]:
arr.ndim

0

In [26]:
arr.shape

()

In [27]:
# 1-D ndarray

In [28]:
xyz = np.array([12, 34, 6, 678, 45, 23, 45])

In [29]:
xyz

array([ 12,  34,   6, 678,  45,  23,  45])

In [30]:
xyz.ndim

1

In [31]:
xyz.shape

(7,)

In [42]:
# z = (12, )

# type(z)

In [43]:
# 2-D ndarray

# is the combination of multiple 1-d ndarray

In [49]:
zx = np.array([[12, 23, 34, 56], [12, 23, 34, 45]])

In [50]:
zx

array([[12, 23, 34, 56],
       [12, 23, 34, 45]])

In [51]:
zx.ndim

2

In [52]:
zx.shape

(2, 4)

In [ ]:
(2, 4)
2-rows, 4 columns

In [62]:
zx = np.array([[12, 3, 45, 56], [23, 34, 45, 34], [34, 54, 67, 78]])

In [63]:
zx

array([[12,  3, 45, 56],
       [23, 34, 45, 34],
       [34, 54, 67, 78]])

In [64]:
zx.ndim

2

In [65]:
zx.shape

(3, 4)

In [67]:
# 3-D ndarray
# combination of multipel 2-d ndarrays

In [80]:
zx = np.array([[[12, 23, 45], [34, 4, 45]], [[34, 45, 67], [34, 45, 23]]])

In [81]:
zx

array([[[12, 23, 45],
        [34,  4, 45]],

       [[34, 45, 67],
        [34, 45, 23]]])

In [82]:
zx.ndim

3

In [83]:
zx.shape

(2, 2, 3)

In [84]:
x = np.array([[[[[[[[[[12]]]]]]]]]])

In [86]:
x.ndim

10