In [1]:
import numpy as np

In [2]:
# ndarrays

In [3]:
arr = np.array([12, 23, 34, 45, 56])

In [4]:
type(arr)

numpy.ndarray

In [5]:
# ndim
# shape

In [6]:
arr.ndim

1

In [7]:
arr.shape

(5,)

In [8]:
# List ---> indexing, slicing

In [9]:
# 1-d Ndarray

In [11]:
xyz = np.array([12, 23, 4, 56, 67, 34, 23, 56, 78])

In [12]:
xyz

array([12, 23,  4, 56, 67, 34, 23, 56, 78])

In [13]:
# syntax for indexing

# array_name[index_number]

In [16]:
xyz[4]

67

In [18]:
xyz[2]

4

In [19]:
# -ve indexing

In [20]:
xyz = np.array([12, 23, 4, 56, 67, 34, 23, 56, 78])

In [21]:
xyz[5]

34

In [22]:
xyz[-4]

34

In [23]:
xyz[-1]

78

In [24]:
# indeixng with 2-D ndarray

In [28]:
arr = np.array([[12, 34, 67, 45, 678], [34, 78, 89, 90, 78]])

In [29]:
arr

array([[ 12,  34,  67,  45, 678],
       [ 34,  78,  89,  90,  78]])

In [30]:
arr.ndim

2

In [31]:
arr.shape

(2, 5)

In [32]:
arr = np.array([[12, 34, 67, 45, 678], [34, 78, 89, 90, 78]])

In [34]:
arr[1]

array([34, 78, 89, 90, 78])

In [35]:
# syntax

# array_name[inner_array_index][element_index]

In [37]:
arr[1][2]

89

In [38]:
arr[1][-3]

89

In [40]:
arr = np.array([[12, 34, 67, 45, 678], [34, 78, 89, 90, 78], [56, 34, 23, 12, 6777]])

In [41]:
arr[2][-1]

6777

In [42]:
# indexing with 3-d

In [55]:
zx = np.array([[[12, 34, 56], [34, 45, 67], [67, 45, 34]], [[45, 34, 45], [45, 45, 23], [45, 3, 23]]])

In [56]:
zx

array([[[12, 34, 56],
        [34, 45, 67],
        [67, 45, 34]],

       [[45, 34, 45],
        [45, 45, 23],
        [45,  3, 23]]])

In [57]:
zx.ndim

3

In [58]:
zx.shape

(2, 3, 3)

In [60]:
zx = np.array(
    [[[12, 34, 56], [34, 45, 67], [67, 45, 34]], [[45, 34, 45], [45, 1, 23], [45, 3, 23]]])

In [63]:
zx[1][1][1]

1

In [64]:
zx[0][-1][0]

67

In [65]:
# Slicing

In [66]:
# array:::::

In [68]:
arr = np.array([12, 34, 45, 67, 78, 9, 0, 34, 56, 67, 89, 34])

In [69]:
# syntax:

# array_name[start_index_number : end_index_number : increment]

In [70]:
arr[2 : 8 : 1]

array([45, 67, 78,  9,  0, 34])

In [ ]:
# slicing ---> default values

start ---> 0
end ---> n - 1
incremnt -----> 1

In [71]:
arr = np.array([12, 34, 45, 67, 78, 9, 0, 34, 56, 67, 89, 34])

In [72]:
arr[ : 6]

array([12, 34, 45, 67, 78,  9])

In [73]:
arr[: : 2]

array([12, 45, 78,  0, 56, 89])

In [74]:
arr = np.array([12, 34, 45, 67, 78, 9, 0, 34, 56, 67, 89, 34])

In [75]:
arr

array([12, 34, 45, 67, 78,  9,  0, 34, 56, 67, 89, 34])

In [76]:
arr[: : -1]

array([34, 89, 67, 56, 34,  0,  9, 78, 67, 45, 34, 12])

In [77]:
arr = np.array([12, 34, 45, 67, 78, 9, 0, 34, 56, 67, 89, 34])

In [ ]:
# 34, 0, 9, 78, 67

In [81]:
arr[-5 : -10 : -1]

array([34,  0,  9, 78, 67])

In [82]:
# 2-D sliing

In [83]:
zx = np.array([[12, 3, 45, 56, 78], [5, 56, 34, 34, 23]])

In [84]:
zx

array([[12,  3, 45, 56, 78],
       [ 5, 56, 34, 34, 23]])

In [86]:
zx[1][1 : 4]

array([56, 34, 34])

In [87]:
# 3:33

In [88]:
# List --->

# mutable ---- modify

# ndarrays ---> mutable


In [89]:
# arange() ---> help to genrate data, from a spacfic point to another point.

In [90]:
# zx = np.arange(start, end, increment)

In [91]:
zx = np.arange(2, 21)

In [92]:
zx

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [94]:
zx = np.arange(2, 21, 3)
zx

array([ 2,  5,  8, 11, 14, 17, 20])

In [95]:
type(zx)

numpy.ndarray

In [96]:
zx.dtype

dtype('int32')

In [97]:
# zeros ---> to create placeholder, 

In [ ]:
pq = np.zeros

In [98]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [100]:
zx = np.zeros(5)
zx

array([0., 0., 0., 0., 0.])

In [102]:
zx = np.zeros((4, 3), dtype=int)
zx

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [103]:
zx = np.zeros((3, 3, 3))
zx

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [104]:
zx.ndim

3

In [105]:
q = np.ones(4)
q

array([1., 1., 1., 1.])

In [106]:
q = np.ones((2, 4))
q

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [108]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9

In [110]:
zx = np.array([[12, 3, 45, 56, 78], [5, 56, 34, 34, 23]])

In [111]:
zx.size

10

In [ ]:
dtype
shape
size 
ndim

In [ ]:
reshape() ------>